#!/bin/sh

mkfifo /tmp/rxQuantum
mkfifo /tmp/txQuantum
mkfifo /tmp/printerQuantum
mkfifo /tmp/gpsQuantum
mkfifo /tmp/RT1

date >> logQuantum.txt
Quantum >> logQuantum.txt  &
date >> bridgeQuantumTCP.txt
nohup bridgeQuantumTCP >> bridgeQuantumTCP.txt &
#date >> logPTIII.txt
#nohup pwrt3lcdapp >> logPTIII.txt &

